// Date: 07.09.2014 15:50:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelUtahraptor extends ModelBase
{
  //fields
    ModelRenderer mouth1;
    ModelRenderer mouth2;
    ModelRenderer head;
    ModelRenderer neck1;
    ModelRenderer neck2;
    ModelRenderer body;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer tail3;
    ModelRenderer tail4;
    ModelRenderer tail5;
    ModelRenderer tail6;
    ModelRenderer leftarm1;
    ModelRenderer leftarm2;
    ModelRenderer leftfinger1;
    ModelRenderer leftfinger2;
    ModelRenderer leftfinger3;
    ModelRenderer rightarm1;
    ModelRenderer rightarm2;
    ModelRenderer rightfinger1;
    ModelRenderer rightfinger2;
    ModelRenderer rightfinger3;
    ModelRenderer leftleg1;
    ModelRenderer leftleg2;
    ModelRenderer leftleg3;
    ModelRenderer leftfoot;
    ModelRenderer leftclaw1;
    ModelRenderer leftclaw2;
    ModelRenderer rightleg1;
    ModelRenderer rightleg2;
    ModelRenderer rightleg3;
    ModelRenderer rightfoot;
    ModelRenderer rightclaw1;
    ModelRenderer rightclaw2;
    ModelRenderer feather1;
    ModelRenderer feather2;
    ModelRenderer feather3;
  
  public ModelUtahraptor()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      mouth1 = new ModelRenderer(this, 17, 2);
      mouth1.addBox(-2F, -3F, -13.4F, 4, 4, 7);
      mouth1.setRotationPoint(0F, -7F, -25.6F);
      mouth1.setTextureSize(128, 128);
      mouth1.mirror = true;
      setRotation(mouth1, 0.1396263F, 0F, 0F);
      mouth2 = new ModelRenderer(this, 17, 16);
      mouth2.addBox(-1.5F, -1.2F, -6.5F, 3, 2, 7);
      mouth2.setRotationPoint(0F, -4F, -32F);
      mouth2.setTextureSize(128, 128);
      mouth2.mirror = true;
      setRotation(mouth2, 0F, 0F, 0F);
      head = new ModelRenderer(this, 45, 2);
      head.addBox(-2.5F, -2.5F, -7F, 5, 6, 7);
      head.setRotationPoint(0F, -7F, -25.56F);
      head.setTextureSize(128, 128);
      head.mirror = true;
      setRotation(head, 0.0523599F, 0F, 0F);
      neck1 = new ModelRenderer(this, 95, 3);
      neck1.addBox(-2F, -2F, -8F, 4, 5, 9);
      neck1.setRotationPoint(0F, -4.5F, -14F);
      neck1.setTextureSize(128, 128);
      neck1.mirror = true;
      setRotation(neck1, -0.3665191F, 0F, 0F);
      neck2 = new ModelRenderer(this, 74, 3);
      neck2.addBox(-2F, -4.2F, -12F, 4, 5, 5);
      neck2.setRotationPoint(0F, -4.5F, -14F);
      neck2.setTextureSize(128, 128);
      neck2.mirror = true;
      setRotation(neck2, -0.0698132F, 0F, 0F);
      body = new ModelRenderer(this, 61, 19);
      body.addBox(-4F, -1.5F, 0F, 8, 11, 24);
      body.setRotationPoint(0F, -5F, -14F);
      body.setTextureSize(128, 128);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      tail1 = new ModelRenderer(this, 1, 58);
      tail1.addBox(-3F, -2F, 0F, 6, 7, 14);
      tail1.setRotationPoint(0F, -4F, 10F);
      tail1.setTextureSize(128, 128);
      tail1.mirror = true;
      setRotation(tail1, 0F, 0F, 0F);
      tail2 = new ModelRenderer(this, 43, 58);
      tail2.addBox(-2.5F, -1.5F, 13.9F, 5, 5, 12);
      tail2.setRotationPoint(0F, -4F, 10F);
      tail2.setTextureSize(128, 128);
      tail2.mirror = true;
      setRotation(tail2, -0.0174533F, 0F, 0F);
      tail3 = new ModelRenderer(this, 80, 58);
      tail3.addBox(-2F, -1F, 25.9F, 4, 4, 13);
      tail3.setRotationPoint(0F, -4F, 10F);
      tail3.setTextureSize(128, 128);
      tail3.mirror = true;
      setRotation(tail3, -0.0174533F, 0F, 0F);
      tail4 = new ModelRenderer(this, 1, 81);
      tail4.addBox(-1.5F, -0.5F, 39F, 3, 3, 12);
      tail4.setRotationPoint(0F, -4F, 10F);
      tail4.setTextureSize(128, 128);
      tail4.mirror = true;
      setRotation(tail4, -0.0174533F, 0F, 0F);
      tail5 = new ModelRenderer(this, 33, 81);
      tail5.addBox(-1F, 0F, 51F, 2, 2, 8);
      tail5.setRotationPoint(0F, -4F, 10F);
      tail5.setTextureSize(128, 128);
      tail5.mirror = true;
      setRotation(tail5, -0.0174533F, 0F, 0F);
      tail6 = new ModelRenderer(this, 33, 95);
      tail6.addBox(-0.5F, 0.5F, 59F, 1, 1, 10);
      tail6.setRotationPoint(0F, -4F, 10F);
      tail6.setTextureSize(128, 128);
      tail6.mirror = true;
      setRotation(tail6, -0.0174533F, 0F, 0F);
      leftarm1 = new ModelRenderer(this, 37, 28);
      leftarm1.addBox(0F, -1F, -1F, 2, 8, 3);
      leftarm1.setRotationPoint(4F, 1.5F, -12F);
      leftarm1.setTextureSize(128, 128);
      leftarm1.mirror = true;
      setRotation(leftarm1, 0.2617994F, 0F, 0F);
      leftarm2 = new ModelRenderer(this, 24, 41);
      leftarm2.addBox(0F, 5F, -7F, 2, 2, 6);
      leftarm2.setRotationPoint(4F, 1.5F, -12F);
      leftarm2.setTextureSize(128, 128);
      leftarm2.mirror = true;
      setRotation(leftarm2, 0.3141593F, 0F, 0F);
      leftfinger1 = new ModelRenderer(this, 0, 0);
      leftfinger1.addBox(0.5F, 2.5F, -11.5F, 1, 1, 3);
      leftfinger1.setRotationPoint(4F, 1.5F, -12F);
      leftfinger1.setTextureSize(128, 128);
      leftfinger1.mirror = true;
      setRotation(leftfinger1, 0.7853982F, -0.0523599F, 0F);
      leftfinger2 = new ModelRenderer(this, 0, 0);
      leftfinger2.addBox(0.5F, 1.5F, -11F, 1, 1, 3);
      leftfinger2.setRotationPoint(4F, 1.5F, -12F);
      leftfinger2.setTextureSize(128, 128);
      leftfinger2.mirror = true;
      setRotation(leftfinger2, 0.7853982F, -0.0698132F, 0F);
      leftfinger3 = new ModelRenderer(this, 0, 5);
      leftfinger3.addBox(0.5F, 1.5F, -10.5F, 1, 1, 2);
      leftfinger3.setRotationPoint(4F, 1.5F, -12F);
      leftfinger3.setTextureSize(128, 128);
      leftfinger3.mirror = true;
      setRotation(leftfinger3, 0.7853982F, 0.122173F, 0F);
      rightarm1 = new ModelRenderer(this, 50, 28);
      rightarm1.addBox(-2F, -1F, -1F, 2, 8, 3);
      rightarm1.setRotationPoint(-4F, 1.5F, -12F);
      rightarm1.setTextureSize(128, 128);
      rightarm1.mirror = true;
      setRotation(rightarm1, 0.2617994F, 0F, 0F);
      rightarm2 = new ModelRenderer(this, 43, 41);
      rightarm2.addBox(-2F, 5F, -7F, 2, 2, 6);
      rightarm2.setRotationPoint(-4F, 1.5F, -12F);
      rightarm2.setTextureSize(128, 128);
      rightarm2.mirror = true;
      setRotation(rightarm2, 0.3141593F, 0F, 0F);
      rightfinger1 = new ModelRenderer(this, 10, 0);
      rightfinger1.addBox(-1.5F, 2.5F, -11.5F, 1, 1, 3);
      rightfinger1.setRotationPoint(-4F, 1.5F, -12F);
      rightfinger1.setTextureSize(128, 128);
      rightfinger1.mirror = true;
      setRotation(rightfinger1, 0.7853982F, 0.0523599F, 0F);
      rightfinger2 = new ModelRenderer(this, 10, 0);
      rightfinger2.addBox(-1.5F, 1.5F, -11F, 1, 1, 3);
      rightfinger2.setRotationPoint(-4F, 1.5F, -12F);
      rightfinger2.setTextureSize(128, 128);
      rightfinger2.mirror = true;
      setRotation(rightfinger2, 0.7853982F, 0.0698132F, 0F);
      rightfinger3 = new ModelRenderer(this, 10, 5);
      rightfinger3.addBox(-1.5F, 1.5F, -10.5F, 1, 1, 2);
      rightfinger3.setRotationPoint(-4F, 1.5F, -12F);
      rightfinger3.setTextureSize(128, 128);
      rightfinger3.mirror = true;
      setRotation(rightfinger3, 0.7853982F, -0.122173F, 0F);
      leftleg1 = new ModelRenderer(this, 57, 81);
      leftleg1.addBox(0F, -2F, -3F, 3, 12, 6);
      leftleg1.setRotationPoint(4F, -0.5F, 4F);
      leftleg1.setTextureSize(128, 128);
      leftleg1.mirror = true;
      setRotation(leftleg1, -0.2094395F, 0F, 0F);
      leftleg2 = new ModelRenderer(this, 57, 101);
      leftleg2.addBox(0F, 7F, -7.5F, 3, 8, 4);
      leftleg2.setRotationPoint(4F, -0.5F, 4F);
      leftleg2.setTextureSize(128, 128);
      leftleg2.mirror = true;
      setRotation(leftleg2, 0.418879F, 0F, 0F);
      leftleg3 = new ModelRenderer(this, 94, 101);
      leftleg3.addBox(0F, 15F, -4.5F, 3, 8, 3);
      leftleg3.setRotationPoint(4F, -0.5F, 4F);
      leftleg3.setTextureSize(128, 128);
      leftleg3.mirror = true;
      setRotation(leftleg3, 0.2443461F, 0F, 0F);
      leftfoot = new ModelRenderer(this, 50, 118);
      leftfoot.addBox(-0.5F, 22.5F, -1F, 4, 2, 5);
      leftfoot.setRotationPoint(4F, -0.5F, 4F);
      leftfoot.setTextureSize(128, 128);
      leftfoot.mirror = true;
      setRotation(leftfoot, 0F, 0F, 0F);
      leftclaw1 = new ModelRenderer(this, 8, 118);
      leftclaw1.addBox(-2.5F, 19.5F, -6F, 1, 3, 1);
      leftclaw1.setRotationPoint(4F, -0.5F, 4F);
      leftclaw1.setTextureSize(128, 128);
      leftclaw1.mirror = true;
      setRotation(leftclaw1, 0.2617994F, 0F, -0.0872665F);
      leftclaw2 = new ModelRenderer(this, 6, 113);
      leftclaw2.addBox(-2.5F, 20F, -6F, 1, 1, 2);
      leftclaw2.setRotationPoint(4F, -0.5F, 4F);
      leftclaw2.setTextureSize(128, 128);
      leftclaw2.mirror = true;
      setRotation(leftclaw2, 0.1745329F, 0F, -0.0872665F);
      rightleg1 = new ModelRenderer(this, 78, 81);
      rightleg1.addBox(-3F, -2F, -3F, 3, 12, 6);
      rightleg1.setRotationPoint(-4F, -0.5F, 4F);
      rightleg1.setTextureSize(128, 128);
      rightleg1.mirror = true;
      setRotation(rightleg1, -0.2094395F, 0F, 0F);
      rightleg2 = new ModelRenderer(this, 78, 101);
      rightleg2.addBox(-3F, 7F, -7.5F, 3, 8, 4);
      rightleg2.setRotationPoint(-4F, -0.5F, 4F);
      rightleg2.setTextureSize(128, 128);
      rightleg2.mirror = true;
      setRotation(rightleg2, 0.418879F, 0F, 0F);
      rightleg3 = new ModelRenderer(this, 109, 101);
      rightleg3.addBox(-3F, 15F, -4.5F, 3, 8, 3);
      rightleg3.setRotationPoint(-4F, -0.5F, 4F);
      rightleg3.setTextureSize(128, 128);
      rightleg3.mirror = true;
      setRotation(rightleg3, 0.2443461F, 0F, 0F);
      rightfoot = new ModelRenderer(this, 77, 118);
      rightfoot.addBox(-3.5F, 22.5F, -1F, 4, 2, 5);
      rightfoot.setRotationPoint(-4F, -0.5F, 4F);
      rightfoot.setTextureSize(128, 128);
      rightfoot.mirror = true;
      setRotation(rightfoot, 0F, 0F, 0F);
      rightclaw1 = new ModelRenderer(this, 16, 118);
      rightclaw1.addBox(1.5F, 19.5F, -6F, 1, 3, 1);
      rightclaw1.setRotationPoint(-4F, -0.5F, 4F);
      rightclaw1.setTextureSize(128, 128);
      rightclaw1.mirror = true;
      setRotation(rightclaw1, 0.2617994F, 0F, 0.0872665F);
      rightclaw2 = new ModelRenderer(this, 16, 113);
      rightclaw2.addBox(1.5F, 20F, -6F, 1, 1, 2);
      rightclaw2.setRotationPoint(-4F, -0.5F, 4F);
      rightclaw2.setTextureSize(128, 128);
      rightclaw2.mirror = true;
      setRotation(rightclaw2, 0.1745329F, 0F, 0.0872665F);
      feather1 = new ModelRenderer(this, 4, 29);
      feather1.addBox(-2.5F, -2.5F, 0F, 5, 1, 4);
      feather1.setRotationPoint(0F, -7F, -25.6F);
      feather1.setTextureSize(128, 128);
      feather1.mirror = true;
      setRotation(feather1, 0.1919862F, 0F, 0F);
      feather2 = new ModelRenderer(this, 13, 36);
      feather2.addBox(-2.5F, -2F, 0F, 1, 5, 4);
      feather2.setRotationPoint(0F, -7F, -25.6F);
      feather2.setTextureSize(128, 128);
      feather2.mirror = true;
      setRotation(feather2, 0.0523599F, -0.2094395F, 0F);
      feather3 = new ModelRenderer(this, 1, 36);
      feather3.addBox(1.5F, -2F, 0F, 1, 5, 4);
      feather3.setRotationPoint(0F, -7F, -25.6F);
      feather3.setTextureSize(128, 128);
      feather3.mirror = true;
      setRotation(feather3, 0.0523599F, 0.2094395F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    mouth1.render(f5);
    mouth2.render(f5);
    head.render(f5);
    neck1.render(f5);
    neck2.render(f5);
    body.render(f5);
    tail1.render(f5);
    tail2.render(f5);
    tail3.render(f5);
    tail4.render(f5);
    tail5.render(f5);
    tail6.render(f5);
    leftarm1.render(f5);
    leftarm2.render(f5);
    leftfinger1.render(f5);
    leftfinger2.render(f5);
    leftfinger3.render(f5);
    rightarm1.render(f5);
    rightarm2.render(f5);
    rightfinger1.render(f5);
    rightfinger2.render(f5);
    rightfinger3.render(f5);
    leftleg1.render(f5);
    leftleg2.render(f5);
    leftleg3.render(f5);
    leftfoot.render(f5);
    leftclaw1.render(f5);
    leftclaw2.render(f5);
    rightleg1.render(f5);
    rightleg2.render(f5);
    rightleg3.render(f5);
    rightfoot.render(f5);
    rightclaw1.render(f5);
    rightclaw2.render(f5);
    feather1.render(f5);
    feather2.render(f5);
    feather3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
