// Date: 8/28/2014 1:52:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.caske2000.carnivores.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelUnknownEggOpen extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
  
  public ModelUnknownEggOpen()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 30, 107);
      Shape1.addBox(0F, 0F, 0F, 17, 3, 17);
      Shape1.setRotationPoint(-8.5F, 21F, -8.5F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 27, 72);
      Shape2.addBox(0F, 0F, 0F, 18, 17, 18);
      Shape2.setRotationPoint(-9F, 4F, -9F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 30, 50);
      Shape3.addBox(0F, 0F, 0F, 16, 3, 16);
      Shape3.setRotationPoint(-8F, 1F, -8F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 35, 31);
      Shape4.addBox(0F, 0F, 0F, 14, 2, 14);
      Shape4.setRotationPoint(-7F, -1F, -7F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 40, 14);
      Shape5.addBox(0F, 0F, 0F, 12, 2, 12);
      Shape5.setRotationPoint(-6F, -3F, -6F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 0);
      Shape6.addBox(-5.5F, 3F, -14F, 11, 0, 9);
      Shape6.setRotationPoint(0F, -3F, 0F);
      Shape6.setTextureSize(128, 128);
      Shape6.mirror = true;
      setRotation(Shape6, -0.5235988F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 12);
      Shape7.addBox(-5.5F, 3F, 5F, 11, 0, 9);
      Shape7.setRotationPoint(0F, -3F, 0F);
      Shape7.setTextureSize(128, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0.5235988F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 90, 0);
      Shape8.addBox(-14F, 3F, -5.5F, 9, 0, 11);
      Shape8.setRotationPoint(0F, -3F, 0F);
      Shape8.setTextureSize(128, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0.5235988F);
      Shape9 = new ModelRenderer(this, 50, 0);
      Shape9.addBox(5F, 3F, -5.5F, 9, 0, 11);
      Shape9.setRotationPoint(0F, -3F, 0F);
      Shape9.setTextureSize(128, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, -0.5235988F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
  }
  
  public void renderModel(float f){
	  	Shape1.render(f);
	    Shape2.render(f);
	    Shape3.render(f);
	    Shape4.render(f);
	    Shape5.render(f);
	    Shape6.render(f);
	    Shape7.render(f);
	    Shape8.render(f);
	    Shape9.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
